import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { montserrat } from "../../public/fonts/font";

export const metadata: Metadata = {
  title: "CSalud",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>{children}</body>
    </html>
  );
}
